import { StyleSheet } from 'react-native';
import { cores } from '../../style-global';

export default StyleSheet.create({
  loader: {
    height: '100%',
  },
  container: {
    flex: 1,
    flexDirection: 'column',
    alignItems: 'center',
  },
  header: {
    flexDirection: 'row',
    padding: 10,
    alignSelf: 'stretch',
    alignItems: 'center',
    justifyContent: 'center',
  },
  containerHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: 250,
    alignItems: 'center',
  },
  subHeader: {
    marginLeft: 10,
  },
  containerHeaderMaster: {
    alignSelf: 'stretch',
    justifyContent: 'flex-start',
  },
  image: {
    alignSelf: 'stretch',
    height: 90,
    alignItems: 'flex-start',
    justifyContent: 'center',
  },
  containerFather: {
    alignSelf: 'stretch',
  },
  body: {
    backgroundColor: cores.cinzaclaro,
    alignSelf: 'stretch',
  },
  icons: {
    flexDirection: 'row',
  },
  optionsIcons: {
    marginRight: 8,
  },
  centeredView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 22,
  },
  modalView: {
    margin: 20,
    alignSelf: 'stretch',
    height: 600,
    backgroundColor: cores.branco,
    borderRadius: 20,
    padding: 35,
    alignItems: 'center',
    shadowColor: cores.preto,
    shadowOffset: {
      width: 500,
      height: 500,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 10,
  },
  textStyle: {
    color: 'white',
    fontWeight: 'bold',
    textAlign: 'center',
  },
  modalText: {
    marginBottom: 15,
    textAlign: 'center',
  },
  containerBody: {
    backgroundColor: cores.branco,
    alignSelf: 'stretch',
    marginTop: 10,
    alignItems: 'center',
    borderRadius: 6,
    marginRight: 10,
    marginLeft: 10,
  },
  containerDivSelect: {
    marginTop: 10,
    flexDirection: 'row',
    alignSelf: 'stretch',
  },
  divSelect: {
    borderRadius: 12,
    alignSelf: 'stretch',
    backgroundColor: '#EDF0F7',
    flex: 1,
    marginLeft: 8,
    marginRight: 8,
  },
  inputSelect: {
    height: 45,
    borderRadius: 10,
    borderColor: cores.cinzaEscuro,
    color: cores.preto,
    padding: 15,
    fontSize: 13,
  },
  divInput: {
    marginTop: 10,
    flexDirection: 'row',
    justifyContent: 'space-around',
    borderStyle: 'solid',
    borderWidth: 1,
    borderColor: cores.preto,
    borderRadius: 50,
    width: 300,
    height: 50,
    alignItems: 'center',
  },
  text: {
    fontSize: 20,
  },
  containerCollector: {
    marginTop: 10,
    alignSelf: 'stretch',
    backgroundColor: '#E1E1E1',
    borderRadius: 5,
    alignItems: 'center',
    marginBottom: 10,
    marginRight: 7,
    marginLeft: 7,
    paddingBottom: 10,
  },
  containerCollectorHeader: {
    marginTop: 10,
    alignSelf: 'stretch',
    flexShrink: 1,
    height: 30,
    backgroundColor: cores.branco,
    borderRadius: 10,
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    marginLeft: 14,
    marginRight: 14,
  },
  spacingBetweenDivs: {
    marginTop: 10,
    marginBottom: 10,
  },
  devices: {
    flexDirection: 'row',
    width: '100%',
    justifyContent: 'space-around',
    marginBottom: 10,
    flexWrap: 'wrap',
  },
  containerCollectorText: {
    color: cores.preto,
    fontWeight: 'bold',
    marginLeft: 10,
    flexShrink: 1,
  },
  containerCollectorBody: {
    marginTop: 10,
    alignSelf: 'stretch',
    backgroundColor: cores.cinzaclaro,
    borderRadius: 10,
    borderBottomColor: cores.verdeEscuro,
    alignItems: 'center',
    marginRight: 7,
    marginLeft: 7,
  },
  containerCollectorBodyTwo: {
    marginTop: 10,
    alignSelf: 'stretch',
    backgroundColor: cores.roxoClaro,
    borderRadius: 10,
    alignItems: 'center',
    // justifyContent: 'center',
    marginBottom: 10,
    marginRight: 7,
    marginLeft: 7,
  },
  containerCell: {
    flexDirection: 'row',
    width: 300,
    height: 35,
    alignItems: 'center',
    marginTop: 5,
    justifyContent: 'space-between',
  },
  iconCell: {
    marginLeft: 10,
  },
  circleGreen: {
    width: 27,
    height: 27,
  },
  containerCellText: {
    color: cores.preto,
    fontWeight: 'bold',
    marginLeft: 8,
    fontSize: 17,
  },
  textEquipment: {
    color: cores.branco,
    fontWeight: 'bold',
    fontSize: 17,
    alignItems: 'center',
    alignSelf: 'stretch',
    height: 25,
    textAlign: 'center',
    backgroundColor: cores.verdeEscuro,
  },
  containerTemperature: {
    flexDirection: 'row',
    alignItems: 'center',
    width: 270,
    height: 40,
    justifyContent: 'center',
  },
  containerTemperatureTwo: {
    flexDirection: 'row',
    alignItems: 'center',
    width: 150,
    height: 40,
    justifyContent: 'center',
  },
  temperature: {
    marginLeft: 10,
    fontWeight: 'bold',
    fontSize: 17,
  },
  temeratureBlock: {
    marginLeft: 10,
    fontWeight: 'bold',
    fontSize: 17,
  },
  containerBadge: {
    marginRight: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  temperaturas: {
    width: 270,
    height: 57,
    flexDirection: 'row',
    borderRadius: 12,
    justifyContent: 'space-evenly',
    alignItems: 'center',
    backgroundColor: cores.branco,
  },
  temperaturasTwo: {
    width: 140,
    height: 57,
    flexDirection: 'row',
    borderRadius: 12,
    justifyContent: 'space-evenly',
    alignItems: 'center',
    backgroundColor: cores.branco,
  },
  temperaturaItem: {
    fontWeight: 'bold',
  },
  minMax: {
    alignItems: 'center',
  },
  coletor: {
    marginTop: 20,
    alignItems: 'center',
    alignSelf: 'stretch',
    height: 25,
    backgroundColor: cores.cinzaDark,
    flexDirection: 'row',
    justifyContent: 'center',
  },
  status: {
    marginTop: 8,
    textAlign: 'center',
    fontWeight: 'bold',
    marginBottom: 8,
  },
  statusTwo: {
    marginTop: 8,
    textAlign: 'center',
    fontWeight: 'bold',
    marginBottom: 20,
  },
  textAmbient: {
    color: cores.branco,
    fontWeight: 'bold',
    fontSize: 17,
    alignItems: 'center',
    alignSelf: 'stretch',
    height: 25,
    textAlign: 'center',
    backgroundColor: cores.roxoEscuro,
  },
  generalTemperatureScreen: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  temperatureScreenOne: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  temperatureScreenTwo: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  CollectorsTexts: {
    color: cores.branco,
    fontWeight: 'bold',
    fontSize: 15,
    textAlign: 'center',
  },
  CollectorsTextsStrings: {
    color: cores.branco,
  },
  containerMasterStatus: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    textAlign: 'center',
  },
  descricaoCollector: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  containerBodyIcon: {
    justifyContent: 'center',
    marginTop: 20,
    alignItems: 'center',
  },
  BodyIcon: {
    alignItems: 'center',
  },
  containerText: {
    marginLeft: 5,
    fontSize: 27,
    color: cores.preto,
    fontWeight: 'bold',
  },
  containerSubHeader: {
    textAlign: 'center',
    color: '#6E7191',
    fontSize: 13,
    alignSelf: 'stretch',
    fontWeight: 'bold',
  },
  collectorButton: {
    padding: 6,
    marginLeft: 6,
    marginRight: 6,
    backgroundColor: cores.roxoEscuro,
    borderRadius: 10,
    color: cores.branco,
    textAlign: 'center',
    fontSize: 17,
    width: '60%',
    alignItems: 'center',
    marginBottom: 10,
  },
  collectorButtonTwo: {
    padding: 6,
    marginLeft: 6,
    marginRight: 6,
    backgroundColor: cores.verdeEscuro,
    borderRadius: 10,
    color: cores.branco,
    textAlign: 'center',
    fontSize: 17,
    width: '60%',
    alignItems: 'center',
    marginBottom: 10,
  },
  buttonCollectorText: {
    color: cores.branco,
    fontWeight: 'bold',
  },
});
